/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.energymanagement.views;
import com.energymanagement.model.EnergyTransaction;
import com.energymanagement.util.ValidationUtil;
import java.util.LinkedList;
import javax.swing.*;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Prashidha
 */
public class EnergyManagementApp extends javax.swing.JFrame {
    
    private java.awt.CardLayout cardLayout;
    private List<EnergyTransaction> energyTransactions;
    
    /**
     * Creates new form NewJFrame
     */
    public EnergyManagementApp() {
//        Image applogo =  new ImageIcon(this.getClass().getResource("/logo.PNG")).getImage();
//        this.setIconImage(applogo);
        setResizable(false);
        setLocation(200,10);
        initComponents();
        initializeLayout();
        startProgress();
        initData();
    }
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlMainHomeScreen, "MainScreen");
        getContentPane().add(pnlLoginScreen, "LoginScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }
    
    private void startProgress() {
        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
        @Override
        protected Void doInBackground() throws Exception {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(30); // Simulated delay
                publish(i); // Update progress
            }
            return null;
        }

        @Override
        protected void process(java.util.List<Integer> chunks) {
            int progress = chunks.get(chunks.size() - 1);
            prgsbarLoading.setValue(progress); // Update the progress bar
        }

        @Override
        protected void done() {
            loadScreen("LoginScreen"); // Load the next screen when done
        }
    };
    worker.execute(); // Start the worker thread
    }  
    
    private void initData() {
    // Initialize the energyTransactions list
    energyTransactions = new LinkedList<>();
    
    // Create a table model with columns
    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{}, // Empty data initially
        new String[]{
            "Transaction ID", "User ID", "Energy Units", "Token Type", 
            "Payment Amount", "Energy Source", "Energy Type", "Location"
        }
    );

    // Set the model to the JTable
    tblEnergyTransactions.setModel(model);
    
    // Add some sample data for demonstration
//    energyTransactions.add(new EnergyTransaction("T001", "U100", 50.0, "TokenA", 100.0, "Solar", "Type1", "Kathmandu"));
//    energyTransactions.add(new EnergyTransaction("T002", "U101", 75.5, "TokenB", 150.0, "Wind", "Type2", "Pokhara"));
//    energyTransactions.add(new EnergyTransaction("T003", "U102", 100.0, "TokenC", 200.0, "Hydro", "Type3", "Lalitpur"));

    // Populate the table with sample data
    for (EnergyTransaction energy : energyTransactions) {
        model.addRow(new Object[]{
            energy.getTransactionId(),
            energy.getUserId(),
            energy.getEnergyUnits(),
            energy.getTokenType(),
            energy.getPaymentAmount(),
            energy.getEnergySource(),
            energy.getEnergyType(),
            energy.getLocation()
        });
    }
}

    
    private void recordEnergyTransaction(EnergyTransaction energy) {
        // Add the transaction to the list
        energyTransactions.add(energy);

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tblEnergyTransactions.getModel();

        // Add a new row with all energy transaction attributes
        model.addRow(new Object[]{
            energy.getTransactionId(),
            energy.getUserId(),
            energy.getEnergyUnits(),
            energy.getTokenType(),
            energy.getPaymentAmount(),
            energy.getEnergySource(),
            energy.getEnergyType(),
            energy.getLocation()
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHomeScreen = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        tabbedPaneMain = new javax.swing.JTabbedPane();
        pnlHomeScreen = new javax.swing.JPanel();
        lblSlogan2 = new javax.swing.JLabel();
        lblSlogan1 = new javax.swing.JLabel();
        lblHomeSubSlogan = new javax.swing.JLabel();
        lblBackgroundImage = new javax.swing.JLabel();
        pnlWhitepaperScreen = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnergyTransactions = new javax.swing.JTable();
        lblTableHeading = new javax.swing.JLabel();
        txtTfldransactionId = new javax.swing.JTextField();
        lblFormHeader = new javax.swing.JLabel();
        txtfldUserId = new javax.swing.JTextField();
        txtfldEnergyUnits = new javax.swing.JTextField();
        cmbTokenType = new javax.swing.JComboBox<>();
        txtfldPaymentAmount = new javax.swing.JTextField();
        cmbEnergySource = new javax.swing.JComboBox<>();
        btnRecordTransaction = new javax.swing.JButton();
        btnRemoveRecords = new javax.swing.JButton();
        btnUpdateRecords = new javax.swing.JButton();
        cmbEnergy = new javax.swing.JComboBox<>();
        txtfldLocation = new javax.swing.JTextField();
        btnClearForm = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        pnlAboutUs = new javax.swing.JPanel();
        pnlLoginScreen = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldLOginUsername = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pwdFldLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lblLoginError = new javax.swing.JLabel();
        pnlLoadingScreen = new javax.swing.JPanel();
        prgsbarLoading = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        pnlMainHomeScreen.setBackground(new java.awt.Color(73, 127, 174));
        pnlMainHomeScreen.setMaximumSize(new java.awt.Dimension(1024, 768));
        pnlMainHomeScreen.setMinimumSize(new java.awt.Dimension(1024, 768));
        pnlMainHomeScreen.setPreferredSize(new java.awt.Dimension(1024, 768));
        pnlMainHomeScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlMainHomeScreen.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 110, 50));

        tabbedPaneMain.setBackground(new java.awt.Color(73, 127, 174));
        tabbedPaneMain.setMaximumSize(new java.awt.Dimension(1024, 768));
        tabbedPaneMain.setMinimumSize(new java.awt.Dimension(1024, 768));
        tabbedPaneMain.setPreferredSize(new java.awt.Dimension(1024, 768));

        pnlHomeScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSlogan2.setBackground(new java.awt.Color(0, 255, 255));
        lblSlogan2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblSlogan2.setForeground(new java.awt.Color(0, 255, 255));
        lblSlogan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan2.setText("Renewable Energy");
        pnlHomeScreen.add(lblSlogan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 480, 70));

        lblSlogan1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblSlogan1.setForeground(new java.awt.Color(51, 255, 255));
        lblSlogan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlogan1.setText("Greener Future With");
        pnlHomeScreen.add(lblSlogan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 570, 77));

        lblHomeSubSlogan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHomeSubSlogan.setText("Now with crypto, we're powering sustainable energy solutions for a decentralized future.");
        pnlHomeScreen.add(lblHomeSubSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 760, -1));

        lblBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/backgr.png"))); // NOI18N
        pnlHomeScreen.add(lblBackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 780));

        tabbedPaneMain.addTab("Home", pnlHomeScreen);

        pnlWhitepaperScreen.setBackground(new java.awt.Color(73, 127, 174));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("<html>\n    <h1>Whitepaper: EnerCoin - Proof of Energy <h1>\n    <be>Introduction</be>\n    <p>\n      Our native token is designed to revolutionize the way energy is utilized within blockchain networks. By implementing a Proof of Energy (PoE) consensus mechanism, we ensure that the energy usage within the network is optimized, reducing waste and increasing efficiency.\n    </p>\n    <br>\n    <be>What is Proof of Energy?</be>\n    <p>\n      Proof of Energy is a novel consensus mechanism that calculates the energy consumption of blockchain operations. Unlike traditional consensus mechanisms, PoE monitors the actual energy used during transactions and mining processes. This approach incentivizes nodes to maintain energy efficiency, thereby promoting sustainable blockchain practices.\n    </p>\n    <br>\n    <be>How PoE Works</be>\n    <p>\n      Nodes within the network are required to report their energy usage to the network’s smart contract. The smart contract then validates these reports and calculates the total energy consumption for the network. Rewards are distributed based on the energy efficiency of each node, incentivizing users to adopt energy-efficient practices.\n    </p>\n    <br>\n    <be>Implementation</be>\n      Our native token is built on a custom blockchain that integrates PoE. The blockchain uses smart contracts to monitor energy usage, and the tokenomics are designed to reward participants for their energy-efficient actions. The protocol will be tested and validated through pilot programs to ensure scalability and reliability.\n<br>\n  </div>\n</html>\n");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/coin.PNG"))); // NOI18N

        javax.swing.GroupLayout pnlWhitepaperScreenLayout = new javax.swing.GroupLayout(pnlWhitepaperScreen);
        pnlWhitepaperScreen.setLayout(pnlWhitepaperScreenLayout);
        pnlWhitepaperScreenLayout.setHorizontalGroup(
            pnlWhitepaperScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhitepaperScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlWhitepaperScreenLayout.setVerticalGroup(
            pnlWhitepaperScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWhitepaperScreenLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlWhitepaperScreenLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("WhitePaper", pnlWhitepaperScreen);

        pnlDashboard.setBackground(new java.awt.Color(73, 127, 174));

        tblEnergyTransactions.setBackground(new java.awt.Color(0, 255, 255));
        tblEnergyTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "TransactionID", "UserID", "EnergyUnits", "TokenType", "PaymentAmount", "Energy", "EnergySource ", "Location"
            }
        ));
        tblEnergyTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnergyTransactionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnergyTransactions);

        lblTableHeading.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTableHeading.setText("Energy Transactions");

        txtTfldransactionId.setBackground(new java.awt.Color(51, 204, 255));
        txtTfldransactionId.setBorder(javax.swing.BorderFactory.createTitledBorder("TransactionID"));
        txtTfldransactionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTfldransactionIdActionPerformed(evt);
            }
        });

        lblFormHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFormHeader.setText("Add ENERGY TRANSACTIONS");

        txtfldUserId.setBackground(new java.awt.Color(51, 204, 255));
        txtfldUserId.setBorder(javax.swing.BorderFactory.createTitledBorder("UserID"));

        txtfldEnergyUnits.setBackground(new java.awt.Color(51, 204, 255));
        txtfldEnergyUnits.setBorder(javax.swing.BorderFactory.createTitledBorder("EnergyUnits"));

        cmbTokenType.setBackground(new java.awt.Color(51, 204, 255));
        cmbTokenType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ETH", "SOL", "BTC", "DOGE", "TRX", "SLC" }));
        cmbTokenType.setBorder(javax.swing.BorderFactory.createTitledBorder("TokenType"));
        cmbTokenType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTokenTypeActionPerformed(evt);
            }
        });

        txtfldPaymentAmount.setBackground(new java.awt.Color(51, 204, 255));
        txtfldPaymentAmount.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Amount"));
        txtfldPaymentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldPaymentAmountActionPerformed(evt);
            }
        });

        cmbEnergySource.setBackground(new java.awt.Color(51, 204, 255));
        cmbEnergySource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solar", "Windmill", "Hydropower", "Nuclear Plant", "Coal Plant", " " }));
        cmbEnergySource.setBorder(javax.swing.BorderFactory.createTitledBorder("EnergySource"));

        btnRecordTransaction.setBackground(new java.awt.Color(51, 204, 255));
        btnRecordTransaction.setText("Add");
        btnRecordTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordTransactionActionPerformed(evt);
            }
        });

        btnRemoveRecords.setBackground(new java.awt.Color(51, 204, 255));
        btnRemoveRecords.setText("Delete");
        btnRemoveRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveRecordsActionPerformed(evt);
            }
        });

        btnUpdateRecords.setBackground(new java.awt.Color(51, 204, 255));
        btnUpdateRecords.setText("Update");
        btnUpdateRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordsActionPerformed(evt);
            }
        });

        cmbEnergy.setBackground(new java.awt.Color(51, 204, 255));
        cmbEnergy.setEditable(true);
        cmbEnergy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricity", "Solar Energy", "Wind Energy", "Hydropower", "Geothermal Energy", "Biomass Energy", "Nuclear Power (General)", "Fusion Reactor", "Fission Reactor", "Tidal Energy" }));
        cmbEnergy.setBorder(javax.swing.BorderFactory.createTitledBorder("Energy"));

        txtfldLocation.setBackground(new java.awt.Color(51, 204, 255));
        txtfldLocation.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));
        txtfldLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldLocationActionPerformed(evt);
            }
        });

        btnClearForm.setBackground(new java.awt.Color(51, 204, 255));
        btnClearForm.setText("Clear");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashboardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTfldransactionId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEnergySource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnRecordTransaction)
                        .addGap(189, 189, 189)
                        .addComponent(btnRemoveRecords)
                        .addGap(193, 193, 193)))
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfldEnergyUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTokenType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addComponent(btnClearForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateRecords)
                        .addGap(108, 108, 108))))
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTableHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTableHeading)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addComponent(lblFormHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                        .addComponent(lblError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTfldransactionId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldEnergyUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTokenType, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                            .addComponent(txtfldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEnergySource, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecordTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Dashboard", pnlDashboard);

        pnlAboutUs.setBackground(new java.awt.Color(73, 127, 174));

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        tabbedPaneMain.addTab("About Us", pnlAboutUs);

        pnlMainHomeScreen.add(tabbedPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 720));

        pnlLoginScreen.setBackground(new java.awt.Color(6, 72, 83));
        pnlLoginScreen.setMaximumSize(new java.awt.Dimension(1024, 768));
        pnlLoginScreen.setMinimumSize(new java.awt.Dimension(1024, 768));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel5.setBackground(new java.awt.Color(2, 136, 138));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jPanel5.setForeground(new java.awt.Color(0, 102, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/solana.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/ethereum.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/capture.PNG"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EnerChain");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(67, 67, 67)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(114, 218, 211));
        jLabel14.setText("Login with your credentials ");

        txtFieldLOginUsername.setText("Username");
        txtFieldLOginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLOginUsernameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(114, 218, 211));
        jLabel16.setText("Username");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(114, 218, 211));
        jLabel17.setText("Password");

        pwdFldLogin.setText("Passsword");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(114, 218, 211));
        jLabel27.setText("Forgot your Password? Register");

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(134, 134, 134))))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17)
                                    .addComponent(txtFieldLOginUsername)
                                    .addComponent(pwdFldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLoginError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(137, 137, 137)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldLOginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1025, 768));
        setMinimumSize(new java.awt.Dimension(1025, 768));
        setPreferredSize(new java.awt.Dimension(1025, 768));

        pnlLoadingScreen.setBackground(new java.awt.Color(2, 136, 138));
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1024, 768));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1024, 768));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1024, 787));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/energymanagement/resources/capture.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EnerChain");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loading...");

        javax.swing.GroupLayout pnlLoadingScreenLayout = new javax.swing.GroupLayout(pnlLoadingScreen);
        pnlLoadingScreen.setLayout(pnlLoadingScreenLayout);
        pnlLoadingScreenLayout.setHorizontalGroup(
            pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingScreenLayout.createSequentialGroup()
                .addGap(587, 587, 587)
                .addComponent(jLabel1)
                .addGap(147, 437, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlLoadingScreenLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(prgsbarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(293, 293, 293))))
        );
        pnlLoadingScreenLayout.setVerticalGroup(
            pnlLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingScreenLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prgsbarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(194, 194, 194))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        loadScreen("LoginScreen");
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtFieldLOginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLOginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLOginUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
//        String username = txtFieldLOginUsername.getText();
//        String password = new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
//        if (username.isEmpty() || password.isEmpty()) {
//            lblLoginError.setText("Please enter your username and password.");
//        } // Check if username and password are incorrect
//        else if (!username.equals("admin") || !password.equals("admin")) {
//            lblLoginError.setText("Username and password mismatch.");
//        } // If credentials are correct, proceed to load the main screen
//        else {
//            lblLoginError.setText(""); // Clear any previous error messages
//            loadScreen("MainScreen"); // Load the main screen
//        }
        loadScreen("MainScreen");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtTfldransactionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTfldransactionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTfldransactionIdActionPerformed

    private void cmbTokenTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTokenTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTokenTypeActionPerformed

    private void txtfldPaymentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldPaymentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldPaymentAmountActionPerformed

    private void txtfldLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldLocationActionPerformed

    private void btnRecordTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordTransactionActionPerformed
        String transactionId = txtTfldransactionId.getText();
        String userId = txtfldUserId.getText();
        String energyUnits = txtfldEnergyUnits.getText();
        String paymentAmount = txtfldPaymentAmount.getText();
        String location = txtfldLocation.getText();
        String tokenType = cmbTokenType.getSelectedItem().toString();
        String energySource = cmbEnergySource.getSelectedItem().toString();
        String energyType = cmbEnergy.getSelectedItem().toString();

        // Validate the inputs using the ValidationUtil methods
        if (ValidationUtil.isValidTransactionId(transactionId, lblError) && 
            ValidationUtil.isValidUserId(userId, lblError) &&
            ValidationUtil.isValidNumericValue(energyUnits, lblError) &&
            ValidationUtil.isValidNumericValue(paymentAmount, lblError) &&
            ValidationUtil.isValidLocation(location, lblError) &&
            ValidationUtil.validatePaymentMethod(tokenType, lblError) &&
            ValidationUtil.isValidEnergySource(energySource, lblError) &&
            ValidationUtil.isValidEnergyType(energyType, lblError)) {

            String transactionIdValue = transactionId;
            String userIdValue = userId;
            double energyUnitsValue = Double.parseDouble(energyUnits);
            double paymentAmountValue = Double.parseDouble(paymentAmount);

            // Create the EnergyTransaction object
            EnergyTransaction transaction = new EnergyTransaction(
                transactionIdValue, 
                userIdValue, 
                energyUnitsValue, 
                tokenType, 
                paymentAmountValue, 
                energySource, 
                energyType, 
                location
            );

            // Record the transaction
            recordEnergyTransaction(transaction);

            // Show success message
            JOptionPane.showMessageDialog(this, "Transaction data has been successfully added.", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Show error message
            JOptionPane.showMessageDialog(this, "Please enter valid data for all fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnRecordTransactionActionPerformed

    private void tblEnergyTransactionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnergyTransactionsMouseClicked
        tblEnergyTransactions.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = tblEnergyTransactions.getSelectedRow();
            if (selectedRow != -1) {
                txtTfldransactionId.setText(tblEnergyTransactions.getValueAt(selectedRow, 0).toString());
                txtfldUserId.setText(tblEnergyTransactions.getValueAt(selectedRow, 1).toString());
                txtfldEnergyUnits.setText(tblEnergyTransactions.getValueAt(selectedRow, 2).toString());
                cmbTokenType.setSelectedItem(tblEnergyTransactions.getValueAt(selectedRow, 3).toString()); 
                txtfldPaymentAmount.setText(tblEnergyTransactions.getValueAt(selectedRow, 4).toString());
                cmbEnergySource.setSelectedItem(tblEnergyTransactions.getValueAt(selectedRow, 5).toString());
                cmbEnergy.setSelectedItem(tblEnergyTransactions.getValueAt(selectedRow, 6).toString());
                txtfldLocation.setText(tblEnergyTransactions.getValueAt(selectedRow, 7).toString());
            }
        }
    });
    }//GEN-LAST:event_tblEnergyTransactionsMouseClicked

    private void btnUpdateRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordsActionPerformed
    int selectedRow = tblEnergyTransactions.getSelectedRow();
        if (selectedRow != -1) {
        	String transactionId = txtTfldransactionId.getText();
        	String userId = txtfldUserId.getText();
        	String energyUnits = txtfldEnergyUnits.getText();
        	String paymentAmount = txtfldPaymentAmount.getText();
        	String location = txtfldLocation.getText();
        	String tokenType = cmbTokenType.getSelectedItem().toString();
        	String energySource = cmbEnergySource.getSelectedItem().toString();
        	String energyType = cmbEnergy.getSelectedItem().toString();

            if (ValidationUtil.isValidTransactionId(transactionId, lblError) && 
            	ValidationUtil.isValidUserId(userId, lblError) &&
            	ValidationUtil.isValidNumericValue(energyUnits, lblError) &&
            	ValidationUtil.isValidNumericValue(paymentAmount, lblError) &&
            	ValidationUtil.isValidLocation(location, lblError) &&
            	ValidationUtil.validatePaymentMethod(tokenType, lblError) &&
            	ValidationUtil.isValidEnergySource(energySource, lblError) &&
            	ValidationUtil.isValidEnergyType(energyType, lblError)) {

                // Update cargo data in the table
                DefaultTableModel model = (DefaultTableModel) tblEnergyTransactions.getModel();
                model.setValueAt(transactionId, selectedRow, 0);
                model.setValueAt(userId, selectedRow, 1);
                model.setValueAt(energyUnits, selectedRow, 2);
                model.setValueAt(paymentAmount, selectedRow, 3);
                model.setValueAt(location, selectedRow, 4);
                model.setValueAt(tokenType, selectedRow, 5);
                model.setValueAt(energySource, selectedRow, 6);
                model.setValueAt(energyType, selectedRow, 7);
                JOptionPane.showMessageDialog(this, "Transaction data updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateRecordsActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
       txtTfldransactionId.setText("");
       txtfldUserId.setText("");
       txtfldEnergyUnits.setText("");
       cmbTokenType.setSelectedIndex(0);
       txtfldPaymentAmount.setText("");
       cmbEnergySource.setSelectedIndex(0);
       cmbEnergy.setSelectedIndex(0);
       txtfldLocation.setText("");
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnRemoveRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRecordsActionPerformed
        String transactionIdToRemove = txtTfldransactionId.getText();
        DefaultTableModel model = (DefaultTableModel) tblEnergyTransactions.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(transactionIdToRemove)) {
                model.removeRow(i);
                break;
            }
        }
    }//GEN-LAST:event_btnRemoveRecordsActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnergyManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnergyManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnergyManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnergyManagementApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnergyManagementApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRecordTransaction;
    private javax.swing.JButton btnRemoveRecords;
    private javax.swing.JButton btnUpdateRecords;
    private javax.swing.JComboBox<String> cmbEnergy;
    private javax.swing.JComboBox<String> cmbEnergySource;
    private javax.swing.JComboBox<String> cmbTokenType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackgroundImage;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFormHeader;
    private javax.swing.JLabel lblHomeSubSlogan;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblSlogan1;
    private javax.swing.JLabel lblSlogan2;
    private javax.swing.JLabel lblTableHeading;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlHomeScreen;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMainHomeScreen;
    private javax.swing.JPanel pnlWhitepaperScreen;
    private javax.swing.JProgressBar prgsbarLoading;
    private javax.swing.JTextField pwdFldLogin;
    private javax.swing.JTabbedPane tabbedPaneMain;
    private javax.swing.JTable tblEnergyTransactions;
    private javax.swing.JTextField txtFieldLOginUsername;
    private javax.swing.JTextField txtTfldransactionId;
    private javax.swing.JTextField txtfldEnergyUnits;
    private javax.swing.JTextField txtfldLocation;
    private javax.swing.JTextField txtfldPaymentAmount;
    private javax.swing.JTextField txtfldUserId;
    // End of variables declaration//GEN-END:variables
}
